version: '3'

services:

  postgres:
    image: postgres:12.3
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=estacionamento
      - POSTGRES_USER=est_user
      - POSTGRES_PASSWORD=est_pass
      - TZ=UTC
